// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cmd

import (
	"github.com/wjhdec/template-server/internal/api/book"
	"github.com/wjhdec/template-server/internal/api/book/repo"
	"github.com/wjhdec/template-server/pkg/dbgorm"
)

// Injectors from wire.go:

func newBookRouter() *book.Router {
	db := newDB()
	bookRepo := repo.New(db)
	handler := book.NewHandler(bookRepo)
	router := book.New(handler)
	return router
}

func newDB() *dbgorm.DB {
	viper := GetConfig()
	options := dbgorm.NewOptions(viper)
	db := dbgorm.New(options)
	return db
}
